### ISSUE TITLE
Can't  understand text in picture

### ISSUE THREAD

**Issue by zavitar8** [blastlaboratory/Metasploit-Reborn#1]
Hello, I am trying to follow the steps but I don't quite understand what it says after step #5 after "Now move metasploit payload which is created and decompiled" 

Thank you!

**Comment by graysuit** [comment]
@zavitar8 sorry, I didn't get notification.

"Now move metasploit payload which is created and decompiled using apktool to folder smali.xxxx. Remove MainActivity.smali"

**Comment by graysuit** [comment]
If I'm NOT wrong, you were also present in discord group `fishes`.
